- name: restart sshd
  service:
    name: ssh
    state: restarted
    enabled: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: reboot_raspi
  reboot:
