- name: "Check external hdd"
  stat:
    path: "{{ external_hdd_device }}"
  register: hdd_device

- name: Get uuid of external hdd
  command: blkid -s UUID -o value {{ external_hdd_device }}
  register: uuid_external_hdd_device
  when: hdd_device.stat.isblk is defined and hdd_device.stat.isblk

- name: "Create directory for external hdd mount point at {{ external_hdd_mount_path }}"
  file:
    path: "{{ external_hdd_mount_path }}"
    state: directory
    mode: '0755'
  when: hdd_device.stat.isblk is defined and hdd_device.stat.isblk

- name: Register external hdd
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      {{ external_hdd_device }} {{ external_hdd_mount_path }} fuseblk rw,nosuid,nodev,noatime,nobootwait,nofail,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 0 0
  when: hdd_device.stat.isblk is defined and hdd_device.stat.isblk
  register: fstab

- name: '/etc/fstab changed, mount everything'
  command: mount -a
  when: fstab.changed

- name: '/etc/fstab changed, remount {{ external_hdd_mount_path }}'
  command: mount -o remount {{ external_hdd_mount_path }}
  when: fstab.changed
